// <auto-generated />
using System;
using GitInsight.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitInsight.Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20221102170358_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("GitInsight.Core.FrequencyDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepositoryCommitDataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryCommitDataId");

                    b.ToTable("FrequencyDTO");
                });

            modelBuilder.Entity("GitInsight.Entities.RepositoryCommitData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReposityCommitData", (string)null);
                });

            modelBuilder.Entity("GitInsight.Core.FrequencyDTO", b =>
                {
                    b.HasOne("GitInsight.Entities.RepositoryCommitData", null)
                        .WithMany("frequencies")
                        .HasForeignKey("RepositoryCommitDataId");
                });

            modelBuilder.Entity("GitInsight.Entities.RepositoryCommitData", b =>
                {
                    b.Navigation("frequencies");
                });
#pragma warning restore 612, 618
        }
    }
}
